# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"

  - script: |
      npm install
      npm run build
      npm test
      npm run report
    displayName: "npm install, build and test"

  - task: PublishTestResults@2
    displayName: "Publish unit test report"
    inputs:
      testResultsFiles: "**/test-report.xml"
    condition: succeededOrFailed()
    continueOnError: true

  - task: PublishCodeCoverageResults@1
    displayName: "Publish test coverage report"
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/coverage/lcov-report"
    condition: succeededOrFailed()
    continueOnError: true

  - task: PublishTestResults@2
    displayName: "Publish the e2e test report"
    inputs:
      testResultsFiles: "**/cypress/e2e-junit-test-report.xml"
    condition: succeededOrFailed()
    continueOnError: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish screenshots when there were issues"
    inputs:
      pathtoPublish: "$(Build.SourcesDirectory)/cypress/screenshots/"
      artifactName: screenshots
    condition: succeededOrFailed()
    continueOnError: true
